; NSIS Installer Script
; Generated by ExeForge HTML to Windows EXE Builder

!define PRODUCT_NAME "Study Hub"
!define PRODUCT_VERSION "1.0.0"
!define PRODUCT_PUBLISHER ""
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\Study Hub.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\Study Hub"

SetCompressor lzma

!include "MUI2.nsh"

Name "Study Hub ${PRODUCT_VERSION}"
OutFile "dist\Study Hub-Setup-${PRODUCT_VERSION}.exe"
InstallDir "$PROGRAMFILES\Study Hub"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File /r "dist\win-unpacked\*"
  CreateDirectory "$SMPROGRAMS\Study Hub"
  CreateShortCut "$SMPROGRAMS\Study Hub\Study Hub.lnk" "$INSTDIR\Study Hub.exe"
  CreateShortCut "$DESKTOP\Study Hub.lnk" "$INSTDIR\Study Hub.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\Study Hub.exe"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "DisplayName" "Study Hub"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "Publisher" ""
SectionEnd

Section Uninstall
  RMDir /r "$INSTDIR"
  Delete "$SMPROGRAMS\Study Hub\Study Hub.lnk"
  RMDir "$SMPROGRAMS\Study Hub"
  Delete "$DESKTOP\Study Hub.lnk"
  DeleteRegKey HKLM "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
SectionEnd
